### ISSUE TITLE
Add HTTP/S check

### ISSUE THREAD

**Issue by teknogeek** [RITC3/Hermes#3]
There needs to be a check for HTTP and HTTPS services. This check should fetch or load the webpage through `requests` or `selenium` in order to ensure that everything is functioning correctly. For verification, this may be done via hashing the entire page contents.

**Comment by nmpiazza** [comment]
Should we split this into 2 different checks, one for HTTP and one for HTTPS. The HTTPS check would check the content of the page, but would also check that TLS is enabled. Also, the TLS check could verify that a specific cert is being used.

**Comment by teknogeek** [comment]
Yeah, sorry there wasn't clarification on this. These should be separate, I just didn't feel a need to separate them into separate issues

**Comment by nmpiazza** [comment]
The argument for keeping them together limits code duplication by adding the TLS checks as an option. As long as the check verification system can handle different parameters to multiple instances of the same check, we should be fine, right?

**Comment by teknogeek** [comment]
Yeah, I think that putting them together is fine. Check out how I did it in the IMAP check: https://github.com/nmpiazza/Hermes/blob/master/app/mod_check/IMAP.py

**Comment by BrandonGDossantos** [comment]
HTTP/S Check pushed to master.
